In [1]:
import json
import pandas as pd 
from pandas.io.json import json_normalize #package for flattening json in pandas df

In [2]:
#load json object
with open('BostonTemplateLibrary.json') as f:
    d = json.load(f)

In [3]:
# GasMaterials
GasMaterials = json_normalize(d['GasMaterials'])
GasMaterials

,$id,Cost,EmbodiedCarbon,EmbodiedCarbonStdDev,EmbodiedEnergy,EmbodiedEnergyStdDev,GasType,Life,Name,SubstitutionRatePattern,SubstitutionTimestep,TransportCarbon,TransportDistance,TransportEnergy,Type
0,1,0.0,0.0,0.0,0.0,0.0,0,1,AIR,[],0.0,0.0,0.0,0.0,Gas
1,2,0.0,0.0,0.0,0.0,0.0,1,1,ARGON,[],0.0,0.0,0.0,0.0,Gas
2,3,0.0,0.0,0.0,0.0,0.0,2,1,KRYPTON,[],0.0,0.0,0.0,0.0,Gas
3,4,0.0,0.0,0.0,0.0,0.0,3,1,XENON,[],0.0,0.0,0.0,0.0,Gas
4,5,0.0,0.0,0.0,0.0,0.0,4,1,SF6,[],0.0,0.0,0.0,0.0,Gas

In [4]:
# GlazingMaterials
GlazingMaterials = json_normalize(d['GlazingMaterials'])
GlazingMaterials

,$id,Comment,Conductivity,Cost,DataSource,Density,DirtFactor,EmbodiedCarbon,EmbodiedCarbonStdDev,EmbodiedEnergy,...,SolarTransmittance,SubstitutionRatePattern,SubstitutionTimestep,TransportCarbon,TransportDistance,TransportEnergy,Type,VisibleReflectanceBack,VisibleReflectanceFront,VisibleTransmittance
0,6,default,0.9,0.0,default,2500.0,1.0,10.10,0.0,191.8,...,0.83,[0.2],50.0,0.067,500.0,0.94,Uncoated,0.08,0.08,0.89
1,7,default,0.9,0.0,default,2500.0,1.0,5.06,0.0,96.1,...,0.83,[0.2],50.0,0.067,500.0,0.94,Uncoated,0.08,0.08,0.89
2,8,default,0.9,0.0,default,2500.0,1.0,5.06,0.0,96.1,...,0.11,[0.2],50.0,0.067,500.0,0.94,Coated,0.35,0.31,0.14
3,9,default,0.9,0.0,default,2500.0,1.0,5.06,0.0,96.1,...,0.63,[0.2],50.0,0.067,500.0,0.94,Coated,0.08,0.06,0.85

In [6]:
# OpaqueMaterials
OpaqueMaterials = json_normalize(d['OpaqueMaterials'])
OpaqueMaterials

,$id,Comment,Conductivity,Cost,DataSource,Density,EmbodiedCarbon,EmbodiedCarbonStdDev,EmbodiedEnergy,EmbodiedEnergyStdDev,...,SubstitutionRatePattern,SubstitutionTimestep,ThermalEmittance,TransportCarbon,TransportDistance,TransportEnergy,Type,VariableConductivity,VariableConductivityProperties,VisibleAbsorptance
0,10,default,0.140,0.0,default,650.0,0.450,0.0,7.40,0.0,...,"[0.5, 1.0]",20.0,0.85,0.067,500.0,0.94,Floorings,False,,0.6
1,11,default,1.250,0.0,default,880.0,0.080,0.0,0.71,0.0,...,[0.2],50.0,0.90,0.067,500.0,0.94,Masonry,False,,0.7
2,12,default,0.100,0.0,default,1.2,0.000,0.0,0.00,0.0,...,[1.0],100.0,0.01,0.000,0.0,0.00,AirCavity,False,,0.7
3,13,default,1.750,0.0,default,2400.0,0.240,0.0,2.12,0.0,...,[1.0],100.0,0.90,0.067,500.0,0.94,Concrete,False,,0.7
4,14,default,1.650,0.0,default,2100.0,0.240,0.0,2.12,0.0,...,[1.0],100.0,0.90,0.067,500.0,0.94,Concrete,False,,0.7
5,15,default,1.770,0.0,default,1900.0,0.080,0.0,0.71,0.0,...,[0.2],50.0,0.90,0.067,500.0,0.94,Masonry,False,,0.7
6,16,default,0.160,0.0,default,950.0,0.380,0.0,6.75,0.0,...,"[0.02, 0.1, 1.0]",20.0,0.90,0.067,500.0,0.94,Boards,False,,0.6
7,17,default,0.410,0.0,default,1000.0,0.220,0.0,3.00,0.0,...,[0.2],50.0,0.90,0.067,500.0,0.94,Masonry,False,,0.5
8,18,default,0.700,0.0,default,1.2,0.000,0.0,0.00,0.0,...,[1.0],100.0,0.01,0.000,0.0,0.00,AirCavity,False,,0.7
9,19,default,0.800,0.0,default,2243.0,0.590,0.0,9.00,0.0,...,"[0.5, 1.0]",20.0,0.90,0.067,500.0,0.94,Floorings,False,,0.4
10,20,default,0.037,0.0,default,40.0,2.700,0.0,86.40,0.0,...,"[0.02, 0.1, 1.0]",20.0,0.60,0.067,500.0,0.94,Insulation,False,,0.6
11,21,default,0.420,0.0,default,900.0,0.240,0.0,3.20,0.0,...,"[0.02, 0.1, 1.0]",20.0,0.90,0.067,500.0,0.94,Plaster,False,,0.7
12,22,default,0.800,0.0,default,1900.0,0.180,0.0,1.34,0.0,...,"[0.02, 0.1, 1.0]",20.0,0.90,0.067,500.0,0.94,Plaster,False,,0.8
13,23,default,0.110,0.0,default,540.0,0.810,0.0,15.00,0.0,...,[0.2],30.0,0.90,0.067,500.0,0.94,Boards,False,,0.7
14,24,default,0.043,0.0,default,12.0,1.350,0.0,28.00,0.0,...,[0.5],30.0,0.90,0.067,1000.0,0.94,Insulation,False,,0.6
15,25,default,0.045,0.0,default,110.0,3.890,0.0,74.40,0.0,...,[1.0],5.0,0.90,0.067,1000.0,0.94,Floorings,False,,0.7
16,26,default,0.160,0.0,default,680.0,0.450,0.0,7.50,0.0,...,"[0.1, 0.1, 1.0]",20.0,0.90,0.067,500.0,0.94,Wood,False,,0.6
17,27,default,0.130,0.0,default,496.0,0.450,0.0,7.50,0.0,...,"[0.1, 0.1, 1.0]",20.0,0.90,0.067,500.0,0.94,Wood,False,,0.6
18,28,default,1.590,0.0,default,1920.0,0.032,0.0,0.55,0.0,...,[1.0],30.0,0.90,0.067,500.0,0.94,Roofings,False,,0.6
19,29,default,0.040,0.0,default,592.0,0.470,0.0,7.80,0.0,...,[1.0],30.0,0.90,0.067,500.0,0.94,Roofings,False,,0.6
20,30,default,0.160,0.0,default,1380.0,2.410,0.0,77.20,0.0,...,[1.0],20.0,0.90,0.067,500.0,0.94,Boards,False,,0.7
21,31,default,45.300,0.0,default,7830.0,1.370,0.0,20.10,0.0,...,[1.0],100.0,0.90,0.067,500.0,0.94,Metals,False,,0.4

In [7]:
OpaqueMaterials.loc[OpaqueMaterials.Name=='B_Gypsum_Board'].iloc[0]

$id                                             16
Comment                                    default
Conductivity                                  0.16
Cost                                             0
DataSource                                 default
Density                                        950
EmbodiedCarbon                                0.38
EmbodiedCarbonStdDev                             0
EmbodiedEnergy                                6.75
EmbodiedEnergyStdDev                             0
Life                                             1
MoistureDiffusionResistance                     50
Name                                B_Gypsum_Board
PhaseChange                                  False
PhaseChangeProperties
Roughness                                    Rough
SolarAbsorptance                               0.6
SpecificHeat                                   840
SubstitutionRatePattern           [0.02, 0.1, 1.0]
SubstitutionTimestep                            20
ThermalEmittance                               0.9
TransportCarbon                              0.067
TransportDistance                              500
TransportEnergy                               0.94
Type                                        Boards
VariableConductivity                         False
VariableConductivityProperties
VisibleAbsorptance                             0.6
Name: 6, dtype: object

In [8]:
# OpaqueConstructions
OpaqueConstructions = json_normalize(d['OpaqueConstructions'])
OpaqueConstructions.sort_values('Name')#[0:8].sort_values('Category')

,$id,AssemblyCarbon,AssemblyCost,AssemblyEnergy,Category,Comments,DataSource,DisassemblyCarbon,DisassemblyEnergy,Layers,Name,Type
5,37,0.0,0.0,0.0,Facade,default,default,0.0,0.0,"[{'Material': {'$ref': '13'}, 'Thickness': 0.2...",B_Off_Bas_0,0
19,51,0.0,0.0,0.0,Exterior Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '13'}, 'Thickness': 0.1...",B_Off_Exf_0,4
3,35,0.0,0.0,0.0,Facade,default,default,0.0,0.0,"[{'Material': {'$ref': '17'}, 'Thickness': 0.0...",B_Off_Fac_0,0
10,42,0.0,0.0,0.0,Ground Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '20'}, 'Thickness': 0.0...",B_Off_Gro_0,2
13,45,0.0,0.0,0.0,Interior Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '25'}, 'Thickness': 0.0...",B_Off_Inf_0,3
16,48,0.0,0.0,0.0,Partition,default,default,0.0,0.0,"[{'Material': {'$ref': '21'}, 'Thickness': 0.0...",B_Off_Par_0,5
7,39,0.0,0.0,0.0,Roof,default,default,0.0,0.0,"[{'Material': {'$ref': '20'}, 'Thickness': 0.1...",B_Off_Rof_0,1
22,54,0.0,0.0,0.0,ThermalMass,default,default,0.0,0.0,"[{'Material': {'$ref': '21'}, 'Thickness': 0.0...",B_Off_Thm_0,0
0,32,0.0,0.0,0.0,Facade,default,default,0.0,0.0,"[{'Material': {'$ref': '13'}, 'Thickness': 0.2...",B_Res_Bas_0,0
15,47,0.0,0.0,0.0,Exterior Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '26'}, 'Thickness': 0.0...",B_Res_Exf_0,4
24,56,0.0,0.0,0.0,Facade,default,default,0.0,0.0,"[{'Material': {'$ref': '17'}, 'Thickness': 0.0...",B_Res_Fac_0_MS,0
1,33,0.0,0.0,0.0,Facade,default,default,0.0,0.0,"[{'Material': {'$ref': '30'}, 'Thickness': 0.0...",B_Res_Fac_0_WF,0
9,41,0.0,0.0,0.0,Ground Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '20'}, 'Thickness': 0.0...",B_Res_Gro_0,2
12,44,0.0,0.0,0.0,Interior Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '10'}, 'Thickness': 0.0...",B_Res_Inf_0,3
18,50,0.0,0.0,0.0,Partition,default,default,0.0,0.0,"[{'Material': {'$ref': '21'}, 'Thickness': 0.0...",B_Res_Par_0,5
6,38,0.0,0.0,0.0,Roof,default,default,0.0,0.0,"[{'Material': {'$ref': '14'}, 'Thickness': 0.1...",B_Res_Rof_0,1
21,53,0.0,0.0,0.0,ThermalMass,default,default,0.0,0.0,"[{'Material': {'$ref': '21'}, 'Thickness': 0.0...",B_Res_Thm_0,0
2,34,0.0,0.0,0.0,Facade,default,default,0.0,0.0,"[{'Material': {'$ref': '13'}, 'Thickness': 0.2...",B_Ret_Bas_0,0
20,52,0.0,0.0,0.0,Exterior Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '13'}, 'Thickness': 0.1...",B_Ret_Exf_0,4
4,36,0.0,0.0,0.0,Facade,default,default,0.0,0.0,"[{'Material': {'$ref': '17'}, 'Thickness': 0.0...",B_Ret_Fac_0,0
11,43,0.0,0.0,0.0,Ground Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '20'}, 'Thickness': 0.0...",B_Ret_Gro_0,2
14,46,0.0,0.0,0.0,Interior Floor,default,default,0.0,0.0,"[{'Material': {'$ref': '25'}, 'Thickness': 0.0...",B_Ret_Inf_0,3
17,49,0.0,0.0,0.0,Partition,default,default,0.0,0.0,"[{'Material': {'$ref': '21'}, 'Thickness': 0.0...",B_Ret_Par_0,5
8,40,0.0,0.0,0.0,Roof,default,default,0.0,0.0,"[{'Material': {'$ref': '20'}, 'Thickness': 0.1...",B_Ret_Rof_0,1
23,55,0.0,0.0,0.0,ThermalMass,default,default,0.0,0.0,"[{'Material': {'$ref': '21'}, 'Thickness': 0.0...",B_Ret_Thm_0,0

In [10]:
OpaqueConstructions.iloc[0]

$id                                                                 32
AssemblyCarbon                                                       0
AssemblyCost                                                         0
AssemblyEnergy                                                       0
Category                                                        Facade
Comments                                                       default
DataSource                                                     default
DisassemblyCarbon                                                    0
DisassemblyEnergy                                                    0
Layers               [{'Material': {'$ref': '13'}, 'Thickness': 0.2...
Name                                                       B_Res_Bas_0
Type                                                                 0
Name: 0, dtype: object

In [10]:
# WindowConstructions
WindowConstructions = json_normalize(d['WindowConstructions'])
WindowConstructions

,$id,AssemblyCarbon,AssemblyCost,AssemblyEnergy,Category,Comments,DataSource,DisassemblyCarbon,DisassemblyEnergy,Layers,Name,Type
0,57,0.0,0.0,0.0,Double,default,default,0.0,0.0,"[{'Material': {'$ref': '7'}, 'Thickness': 0.00...",B_Dbl_Air_Cl,2
1,58,0.0,0.0,0.0,Double,default,default,0.0,0.0,"[{'Material': {'$ref': '9'}, 'Thickness': 0.00...",B_Dbl_Air_Le,2
2,59,0.0,0.0,0.0,Double,default,default,0.0,0.0,"[{'Material': {'$ref': '7'}, 'Thickness': 0.00...",B_Dbl_Arg_Cl,2
3,60,0.0,0.0,0.0,Double,default,default,0.0,0.0,"[{'Material': {'$ref': '9'}, 'Thickness': 0.00...",B_Dbl_Arg_Le,2
4,61,0.0,0.0,0.0,Single,default,default,0.0,0.0,"[{'Material': {'$ref': '6'}, 'Thickness': 0.004}]",B_Sng_Cl,1

In [11]:
WindowConstructions.iloc[0,9]

[{'Material': {'$ref': '7'}, 'Thickness': 0.003},
 {'Material': {'$ref': '1'}, 'Thickness': 0.006},
 {'Material': {'$ref': '7'}, 'Thickness': 0.003}]

In [12]:
# StructureDefinitions
StructureDefinitions = json_normalize(d['StructureDefinitions'])
StructureDefinitions

,$id,AssemblyCarbon,AssemblyCost,AssemblyEnergy,Category,Comments,DataSource,DisassemblyCarbon,DisassemblyEnergy,MassRatios,Name
0,62,0.0,0.0,0.0,Steel,default,default,0.0,0.0,"[{'HighLoadRatio': 305.0, 'Material': {'$ref':...",B_Off_Str_0
1,63,0.0,0.0,0.0,Steel,default,default,0.0,0.0,"[{'HighLoadRatio': 305.0, 'Material': {'$ref':...",B_Ret_Str_0
2,64,0.0,0.0,0.0,Timber,default,default,0.0,0.0,"[{'HighLoadRatio': 5.0, 'Material': {'$ref': '...",B_Res_Str_W_0
3,65,0.0,0.0,0.0,Steel,default,default,0.0,0.0,"[{'HighLoadRatio': 305.0, 'Material': {'$ref':...",B_Res_Str_S_0

In [13]:
# DaySchedules
DaySchedules = json_normalize(d['DaySchedules'])
DaySchedules

,$id,Category,Comments,DataSource,Name,Type,Values
0,66,Day,default,default,hourlyAllOn,Fraction,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
1,67,Day,default,default,B_Res_D_Occ_WD,Fraction,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.3, ..."
2,68,Day,default,default,B_Res_D_Occ_WE,Fraction,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
3,69,Day,default,default,B_Res_D_Lgt_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.5, 0.5, ..."
4,70,Day,default,default,B_Res_D_Lgt_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, ..."
5,71,Day,default,default,B_Res_D_Plg_WD,Fraction,"[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.6, 0.6, 0.4, ..."
6,72,Day,default,default,B_Res_D_Plg_WE,Fraction,"[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.6, ..."
7,73,Day,default,default,B_Res_D_Dhw_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, ..."
8,74,Day,default,default,B_Res_D_Dhw_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, ..."
9,75,Day,default,default,B_Res_D_Het_WD,Fraction,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
10,76,Day,default,default,B_Res_D_Het_WE,Fraction,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
11,77,Day,default,default,B_Res_D_Col_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
12,78,Day,default,default,B_Res_D_Col_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
13,79,Day,default,default,B_Res_D_Nat_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ..."
14,80,Day,default,default,B_Res_D_Nat_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ..."
15,81,Day,default,default,B_Res_D_Off,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
16,82,Day,default,default,B_Off_D_Occ_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.2, 1.0, ..."
17,83,Day,default,default,B_Off_D_Occ_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, ..."
18,84,Day,default,default,B_Off_D_Lgt_WD,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 1.0, ..."
19,85,Day,default,default,B_Off_D_Lgt_WE,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, ..."
20,86,Day,default,default,B_Off_D_Plg_WD,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 1.0, ..."
21,87,Day,default,default,B_Off_D_Plg_WE,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, ..."
22,88,Day,default,default,B_Off_D_Dhw_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.4, 0.4, ..."
23,89,Day,default,default,B_Off_D_Dhw_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, ..."
24,90,Day,default,default,B_Off_D_Het_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, ..."
25,91,Day,default,default,B_Off_D_Het_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
26,92,Day,default,default,B_Off_D_Col_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, ..."
27,93,Day,default,default,B_Off_D_Col_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
28,94,Day,default,default,B_Off_D_Nat_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, ..."
29,95,Day,default,default,B_Off_D_Nat_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
30,96,Day,default,default,B_Off_D_Off,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
31,97,Day,default,default,B_Ret_D_Occ_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.4, ..."
32,98,Day,default,default,B_Ret_D_Occ_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
33,99,Day,default,default,B_Ret_D_Lgt_WD,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.6, ..."
34,100,Day,default,default,B_Ret_D_Lgt_WE,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, ..."
35,101,Day,default,default,B_Ret_D_Plg_WD,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.6, ..."
36,102,Day,default,default,B_Ret_D_Plg_WE,Fraction,"[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, ..."
37,103,Day,default,default,B_Ret_D_Dhw_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, ..."
38,104,Day,default,default,B_Ret_D_Dhw_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
39,105,Day,default,default,B_Ret_D_Het_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ..."
40,106,Day,default,default,B_Ret_D_Het_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
41,107,Day,default,default,B_Ret_D_Col_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ..."
42,108,Day,default,default,B_Ret_D_Col_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
43,109,Day,default,default,B_Ret_D_Nat_WD,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
44,110,Day,default,default,B_Ret_D_Nat_WE,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
45,111,Day,default,default,B_Ret_D_Off,Fraction,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [14]:
# WeekSchedules
WeekSchedules = json_normalize(d['WeekSchedules'])
WeekSchedules

,$id,Category,Comments,DataSource,Days,Name,Type
0,112,Week,default,default,"[{'$ref': '66'}, {'$ref': '66'}, {'$ref': '66'...",weekAllOn,Fraction
1,113,Week,default,default,"[{'$ref': '67'}, {'$ref': '67'}, {'$ref': '67'...",B_Res_W_Occ,Fraction
2,114,Week,default,default,"[{'$ref': '69'}, {'$ref': '69'}, {'$ref': '69'...",B_Res_W_Lgt,Fraction
3,115,Week,default,default,"[{'$ref': '71'}, {'$ref': '71'}, {'$ref': '71'...",B_Res_W_Plg,Fraction
4,116,Week,default,default,"[{'$ref': '73'}, {'$ref': '73'}, {'$ref': '73'...",B_Res_W_Dhw,Fraction
5,117,Week,default,default,"[{'$ref': '75'}, {'$ref': '75'}, {'$ref': '75'...",B_Res_W_Het,Fraction
6,118,Week,default,default,"[{'$ref': '77'}, {'$ref': '77'}, {'$ref': '77'...",B_Res_W_Col,Fraction
7,119,Week,default,default,"[{'$ref': '79'}, {'$ref': '79'}, {'$ref': '79'...",B_Res_W_Nat,Fraction
8,120,Week,default,default,"[{'$ref': '81'}, {'$ref': '81'}, {'$ref': '81'...",B_Res_W_Off,Fraction
9,121,Week,default,default,"[{'$ref': '82'}, {'$ref': '82'}, {'$ref': '82'...",B_Off_W_Occ,Fraction
10,122,Week,default,default,"[{'$ref': '84'}, {'$ref': '84'}, {'$ref': '84'...",B_Off_W_Lgt,Fraction
11,123,Week,default,default,"[{'$ref': '86'}, {'$ref': '86'}, {'$ref': '86'...",B_Off_W_Plg,Fraction
12,124,Week,default,default,"[{'$ref': '88'}, {'$ref': '88'}, {'$ref': '88'...",B_Off_W_Dhw,Fraction
13,125,Week,default,default,"[{'$ref': '90'}, {'$ref': '90'}, {'$ref': '90'...",B_Off_W_Het,Fraction
14,126,Week,default,default,"[{'$ref': '92'}, {'$ref': '92'}, {'$ref': '92'...",B_Off_W_Col,Fraction
15,127,Week,default,default,"[{'$ref': '94'}, {'$ref': '94'}, {'$ref': '94'...",B_Off_W_Nat,Fraction
16,128,Week,default,default,"[{'$ref': '96'}, {'$ref': '96'}, {'$ref': '96'...",B_Off_W_Off,Fraction
17,129,Week,default,default,"[{'$ref': '97'}, {'$ref': '97'}, {'$ref': '97'...",B_Ret_W_Occ,Fraction
18,130,Week,default,default,"[{'$ref': '99'}, {'$ref': '99'}, {'$ref': '99'...",B_Ret_W_Lgt,Fraction
19,131,Week,default,default,"[{'$ref': '101'}, {'$ref': '101'}, {'$ref': '1...",B_Ret_W_Plg,Fraction
20,132,Week,default,default,"[{'$ref': '103'}, {'$ref': '103'}, {'$ref': '1...",B_Ret_W_Dhw,Fraction
21,133,Week,default,default,"[{'$ref': '105'}, {'$ref': '105'}, {'$ref': '1...",B_Ret_W_Het,Fraction
22,134,Week,default,default,"[{'$ref': '107'}, {'$ref': '107'}, {'$ref': '1...",B_Ret_W_Col,Fraction
23,135,Week,default,default,"[{'$ref': '109'}, {'$ref': '109'}, {'$ref': '1...",B_Ret_W_Nat,Fraction
24,136,Week,default,default,"[{'$ref': '111'}, {'$ref': '111'}, {'$ref': '1...",B_Ret_W_Off,Fraction

In [15]:
# YearSchedules
YearSchedules = json_normalize(d['YearSchedules'])
YearSchedules

,$id,Category,Comments,DataSource,Name,Parts,Type
0,137,Year,default,default,AllOn,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
1,138,Year,default,default,B_Res_Y_Occ,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
2,139,Year,default,default,B_Res_Y_Lgt,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
3,140,Year,default,default,B_Res_Y_Plg,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
4,141,Year,default,default,B_Res_Y_Dhw,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
5,142,Year,default,default,B_Res_Y_Het,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 30, '...",Fraction
6,143,Year,default,default,B_Res_Y_Col,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 30, '...",Fraction
7,144,Year,default,default,B_Res_Y_Nat,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 30, '...",Fraction
8,145,Year,default,default,B_Off_Y_Occ,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
9,146,Year,default,default,B_Off_Y_Lgt,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
10,147,Year,default,default,B_Off_Y_Plg,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
11,148,Year,default,default,B_Off_Y_Dhw,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
12,149,Year,default,default,B_Off_Y_Het,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 30, '...",Fraction
13,150,Year,default,default,B_Off_Y_Col,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
14,151,Year,default,default,B_Off_Y_Nat,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
15,152,Year,default,default,B_Ret_Y_Occ,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
16,153,Year,default,default,B_Ret_Y_Lgt,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
17,154,Year,default,default,B_Ret_Y_Plg,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
18,155,Year,default,default,B_Ret_Y_Dhw,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 31, '...",Fraction
19,156,Year,default,default,B_Ret_Y_Het,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 30, '...",Fraction
20,157,Year,default,default,B_Ret_Y_Col,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 30, '...",Fraction
21,158,Year,default,default,B_Ret_Y_Nat,"[{'FromDay': 1, 'FromMonth': 1, 'ToDay': 30, '...",Fraction

In [16]:
# DomesticHotWaterSettings
DomesticHotWaterSettings = json_normalize(d['DomesticHotWaterSettings'])
DomesticHotWaterSettings

,$id,Category,DataSource,FlowRatePerFloorArea,IsOn,Name,WaterSchedule.$ref,WaterSupplyTemperature,WaterTemperatureInlet
0,159,Office Spaces,MIT_SDL,0.00021,True,B_Off_0 hot water,148,55.0,16.0
1,160,Retail,MIT_SDL,0.00006,True,B_Ret_0 hot water,155,55.0,16.0
2,161,Residential and Lodging,MIT_SDL,0.00049,True,B_Res_0 hot water,141,55.0,16.0

In [28]:
# VentilationSettings
VentilationSettings = json_normalize(d['VentilationSettings'])
VentilationSettings

,$id,Afn,Category,DataSource,Infiltration,IsBuoyancyOn,IsInfiltrationOn,IsNatVentOn,IsScheduledVentilationOn,IsWindOn,Name,NatVentMaxOutdoorAirTemp,NatVentMaxRelHumidity,NatVentMinOutdoorAirTemp,NatVentSchedule.$ref,NatVentZoneTempSetpoint,ScheduledVentilationAch,ScheduledVentilationSchedule.$ref,ScheduledVentilationSetpoint
0,162,False,Office Spaces,MIT_SDL,0.35,True,True,False,False,False,B_Off_0 ventilation,26.0,80.0,20.0,151,22.0,0.6,151,22.0
1,163,False,Retail,MIT_SDL,0.35,True,True,False,False,False,B_Ret_0 ventilation,26.0,80.0,20.0,158,22.0,0.6,158,22.0
2,164,False,Residential and Lodging,MIT_SDL,0.35,True,True,False,False,False,B_Res_0 ventilation,26.0,80.0,18.0,144,22.0,0.6,144,22.0

In [12]:
# ZoneConditionings
ZoneConditionings = json_normalize(d['ZoneConditionings'])
ZoneConditionings

,$id,Category,CoolingCoeffOfPerf,CoolingLimitType,CoolingSchedule.$ref,CoolingSetpoint,DataSource,EconomizerType,HeatRecoveryEfficiencyLatent,HeatRecoveryEfficiencySensible,...,IsHeatingOn,IsMechVentOn,MaxCoolFlow,MaxCoolingCapacity,MaxHeatFlow,MaxHeatingCapacity,MechVentSchedule.$ref,MinFreshAirPerArea,MinFreshAirPerPerson,Name
0,165,Office Spaces,3.0,0,150,24.0,MIT_SDL,0,0.65,0.7,...,True,True,100.0,100.0,100.0,100.0,145,0.0003,0.0025,B_Off_0 conditioning
1,166,Retail,3.0,0,157,24.0,MIT_SDL,0,0.65,0.7,...,True,True,100.0,100.0,100.0,100.0,152,0.0006,0.0000,B_Ret_0 conditioning
2,167,Residential and Lodging,3.0,0,143,24.0,MIT_SDL,0,0.65,0.7,...,True,False,100.0,100.0,100.0,100.0,138,0.0000,0.0000,B_Res_0 conditioning

In [19]:
# ZoneConstructionSets
ZoneConstructionSets = json_normalize(d['ZoneConstructionSets'])
ZoneConstructionSets

,$id,Category,DataSource,Facade.$ref,Ground.$ref,IsFacadeAdiabatic,IsGroundAdiabatic,IsPartitionAdiabatic,IsRoofAdiabatic,IsSlabAdiabatic,Name,Partition.$ref,Roof.$ref,Slab.$ref
0,168,Office Spaces,MIT_SDL,35,42,False,False,False,False,False,B_Off_0 constructions,48,39,45
1,169,Retail,MIT_SDL,36,43,False,False,False,False,False,B_Ret_0 constructions,49,40,46
2,170,Residential and Lodging,MIT_SDL,56,41,False,False,False,False,False,B_Res_0_MS constructions,50,38,44
3,171,Residential and Lodging,MIT_SDL,33,41,False,False,False,False,False,B_Res_0_WF constructions,50,38,44

In [20]:
# ZoneLoads
ZoneLoads = json_normalize(d['ZoneLoads'])
ZoneLoads

,$id,Category,DataSource,DimmingType,EquipmentAvailabilitySchedule.$ref,EquipmentPowerDensity,IlluminanceTarget,IsEquipmentOn,IsLightingOn,IsPeopleOn,LightingPowerDensity,LightsAvailabilitySchedule.$ref,Name,OccupancySchedule.$ref,PeopleDensity
0,172,Office Spaces,MIT_SDL,1,147,8.0,500.0,True,True,True,12.0,146,B_Off_0 loads,145,0.055
1,173,Retail,MIT_SDL,1,154,6.0,300.0,True,True,True,16.0,154,B_Ret_0 loads,152,0.100
2,174,Residential and Lodging,MIT_SDL,1,140,4.0,200.0,True,True,True,7.0,139,B_Res_0 loads,138,0.025

In [21]:
# Zones
Zones = json_normalize(d['Zones'])
Zones

,$id,Category,Conditioning.$ref,Constructions.$ref,DataSource,DaylightMeshResolution,DaylightWorkplaneHeight,DomesticHotWater.$ref,InternalMassConstruction.$ref,InternalMassExposedPerFloorArea,Loads.$ref,Name,Ventilation.$ref
0,175,Office Spaces,165,168,MIT_SDL,1.0,0.8,159,54,1.05,172,B_Off_0,162
1,176,Retail,166,169,MIT_SDL,1.0,0.8,160,55,0.45,173,B_Ret_0,163
2,177,Residential and Lodging,167,170,MIT_SDL,1.0,0.8,161,53,0.90,174,B_Res_0_MS,164
3,178,Residential and Lodging,167,171,MIT_SDL,1.0,0.8,161,53,0.90,174,B_Res_0_WF,164

In [22]:
# BuildingTemplates
BuildingTemplates = json_normalize(d['BuildingTemplates'])
BuildingTemplates.set_index(['Name'])

,Category,Comments,Core.$ref,DataSource,Lifespan,PartitionRatio,Perimeter.$ref,Structure.$ref,Windows.$id,Windows.$ref,...,Windows.Name,Windows.OperableArea,Windows.ShadingSystemAvailabilitySchedule.$ref,Windows.ShadingSystemSetpoint,Windows.ShadingSystemTransmittance,Windows.ShadingSystemType,Windows.Type,Windows.ZoneMixingAvailabilitySchedule.$ref,Windows.ZoneMixingDeltaTemperature,Windows.ZoneMixingFlowRate
Name,,,,,,,,,,,,,,,,,,,,,
B_Off_0,Office Spaces,Base building definition for MIT 4433,175,MIT_SDL,60,0.35,175,62,179,NaN,...,B_Off_0 windows,0.8,145,350.0,0.5,0.0,0.0,145,2.0,0.001
B_Ret_0,Retail,Base building definition for MIT 4433,176,MIT_SDL,60,0.15,176,63,180,NaN,...,B_Ret_0 windows,0.8,152,0.5,0.5,0.0,0.0,152,2.0,0.001
B_Res_0_Masonry,Residential and Lodging,Base building definition for MIT 4433,177,MIT_SDL,60,0.30,177,65,181,NaN,...,B_Res_0 windows,0.8,138,0.5,0.5,0.0,0.0,138,2.0,0.001
B_Res_0_WoodFrame,Residential and Lodging,Base building definition for MIT 4433,178,MIT_SDL,60,0.30,178,64,NaN,181,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
BuildingTemplates.loc[:,['Core.$ref','Perimeter.$ref']]

  Core.$ref Perimeter.$ref
0       175            175
1       176            176
2       177            177
3       178            178

In [24]:
list(BuildingTemplates.columns)

['Category',
 'Comments',
 'Core.$ref',
 'DataSource',
 'Lifespan',
 'Name',
 'PartitionRatio',
 'Perimeter.$ref',
 'Structure.$ref',
 'Windows.$id',
 'Windows.$ref',
 'Windows.AfnDischargeC',
 'Windows.AfnTempSetpoint',
 'Windows.AfnWindowAvailability.$ref',
 'Windows.Category',
 'Windows.Comments',
 'Windows.Construction.$ref',
 'Windows.DataSource',
 'Windows.IsShadingSystemOn',
 'Windows.IsVirtualPartition',
 'Windows.IsZoneMixingOn',
 'Windows.Name',
 'Windows.OperableArea',
 'Windows.ShadingSystemAvailabilitySchedule.$ref',
 'Windows.ShadingSystemSetpoint',
 'Windows.ShadingSystemTransmittance',
 'Windows.ShadingSystemType',
 'Windows.Type',
 'Windows.ZoneMixingAvailabilitySchedule.$ref',
 'Windows.ZoneMixingDeltaTemperature',
 'Windows.ZoneMixingFlowRate']

In [25]:
# WindowSettings
WindowSettings = json_normalize(d['WindowSettings'])
WindowSettings

  $ref
0  179
1  180
2  181

## Writing JSON to file

In [26]:
with open('python-template-library.json', 'w') as f:
        json.dump(d, f, indent=True)